/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/-/litestream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/-/litestream/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Running */
                            running: boolean;
                            /**
                             * Can Manage
                             * @default null
                             */
                            can_manage?: boolean | null;
                            /**
                             * Metrics Enabled
                             * @default null
                             */
                            metrics_enabled?: boolean | null;
                            /** @default null */
                            daemon?: components["schemas"]["DaemonInfo"] | null;
                            /**
                             * Socket Error
                             * @default null
                             */
                            socket_error?: string | null;
                            /**
                             * Databases
                             * @default null
                             */
                            databases?: components["schemas"]["ManagedDatabase"][] | null;
                            /**
                             * Available
                             * @default null
                             */
                            available?: components["schemas"]["AvailableDatabase"][] | null;
                            /**
                             * Warnings
                             * @default null
                             */
                            warnings?: string[] | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/-/litestream/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Database */
                        database: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Ok */
                            ok: boolean;
                            /**
                             * Error
                             * @default null
                             */
                            error?: string | null;
                            /**
                             * Details
                             * @default null
                             */
                            details?: string | null;
                            /**
                             * Database
                             * @default null
                             */
                            database?: string | null;
                            /**
                             * Path
                             * @default null
                             */
                            path?: string | null;
                            /**
                             * Replica
                             * @default null
                             */
                            replica?: string | null;
                            /**
                             * Status
                             * @default null
                             */
                            status?: string | null;
                            /**
                             * Txid
                             * @default null
                             */
                            txid?: unknown | null;
                            /**
                             * Result
                             * @default null
                             */
                            result?: unknown | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/-/litestream/api/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Database */
                        database: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Ok */
                            ok: boolean;
                            /**
                             * Error
                             * @default null
                             */
                            error?: string | null;
                            /**
                             * Details
                             * @default null
                             */
                            details?: string | null;
                            /**
                             * Database
                             * @default null
                             */
                            database?: string | null;
                            /**
                             * Path
                             * @default null
                             */
                            path?: string | null;
                            /**
                             * Replica
                             * @default null
                             */
                            replica?: string | null;
                            /**
                             * Status
                             * @default null
                             */
                            status?: string | null;
                            /**
                             * Txid
                             * @default null
                             */
                            txid?: unknown | null;
                            /**
                             * Result
                             * @default null
                             */
                            result?: unknown | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/-/litestream/api/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Database */
                        database: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Ok */
                            ok: boolean;
                            /**
                             * Error
                             * @default null
                             */
                            error?: string | null;
                            /**
                             * Details
                             * @default null
                             */
                            details?: string | null;
                            /**
                             * Database
                             * @default null
                             */
                            database?: string | null;
                            /**
                             * Path
                             * @default null
                             */
                            path?: string | null;
                            /**
                             * Replica
                             * @default null
                             */
                            replica?: string | null;
                            /**
                             * Status
                             * @default null
                             */
                            status?: string | null;
                            /**
                             * Txid
                             * @default null
                             */
                            txid?: unknown | null;
                            /**
                             * Result
                             * @default null
                             */
                            result?: unknown | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/-/litestream/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Database */
                        database: string;
                        /**
                         * Replica
                         * @default null
                         */
                        replica?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Ok */
                            ok: boolean;
                            /**
                             * Error
                             * @default null
                             */
                            error?: string | null;
                            /**
                             * Details
                             * @default null
                             */
                            details?: string | null;
                            /**
                             * Database
                             * @default null
                             */
                            database?: string | null;
                            /**
                             * Path
                             * @default null
                             */
                            path?: string | null;
                            /**
                             * Replica
                             * @default null
                             */
                            replica?: string | null;
                            /**
                             * Status
                             * @default null
                             */
                            status?: string | null;
                            /**
                             * Txid
                             * @default null
                             */
                            txid?: unknown | null;
                            /**
                             * Result
                             * @default null
                             */
                            result?: unknown | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/-/litestream/unregister": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Database */
                        database: string;
                        /**
                         * Timeout
                         * @default null
                         */
                        timeout?: number | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Ok */
                            ok: boolean;
                            /**
                             * Error
                             * @default null
                             */
                            error?: string | null;
                            /**
                             * Details
                             * @default null
                             */
                            details?: string | null;
                            /**
                             * Database
                             * @default null
                             */
                            database?: string | null;
                            /**
                             * Path
                             * @default null
                             */
                            path?: string | null;
                            /**
                             * Replica
                             * @default null
                             */
                            replica?: string | null;
                            /**
                             * Status
                             * @default null
                             */
                            status?: string | null;
                            /**
                             * Txid
                             * @default null
                             */
                            txid?: unknown | null;
                            /**
                             * Result
                             * @default null
                             */
                            result?: unknown | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/-/litestream-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AvailableDatabase
         * @description An attached, file-backed database not currently replicating.
         */
        AvailableDatabase: {
            /** Database */
            database: string;
            /** Path */
            path: string;
            /**
             * Suggested Replica
             * @default null
             */
            suggested_replica?: string | null;
        };
        /**
         * DaemonInfo
         * @description Daemon-level info reported by litestream's control socket.
         */
        DaemonInfo: {
            /** Version */
            version: string;
            /** Pid */
            pid: number;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Started At */
            started_at: string;
            /** Database Count */
            database_count: number;
        };
        /**
         * ManagedDatabase
         * @description A database currently registered with the litestream daemon.
         */
        ManagedDatabase: {
            /**
             * Database
             * @default null
             */
            database?: string | null;
            /** Path */
            path: string;
            /**
             * Status
             * @default null
             */
            status?: string | null;
            /**
             * Last Sync At
             * @default null
             */
            last_sync_at?: string | null;
            /**
             * Replica
             * @default null
             */
            replica?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
