name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v5
      - id: cache-litestream
        uses: actions/cache@v3
        with:
          path: $HOME/.local/bin/litestream
          key: ${{ runner.os }}-primes
      - run: mkdir -p $HOME/.local/bin
      - if: steps.cache-litestream.outputs.cache-hit != 'true'
        run: curl -L https://github.com/benbjohnson/litestream/releases/download/v0.3.11/litestream-v0.3.11-linux-amd64.tar.gz |tar -xz -C $HOME/.local/bin
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Run tests
        run: |
          uv run python -m pytest
